%define module httptools
%bcond_without test

Name:		python-httptools
Version:	0.6.4
Release:	1
Summary:	A Python binding for the nodejs HTTP parser
URL:		https://pypi.org/project/httptools/
License:	MIT
Group:		Development/Python
Source0:	https://files.pythonhosted.org/packages/source/h/httptools/httptools-%{version}.tar.gz
BuildSystem:	python

BuildRequires: python
BuildRequires: pkgconfig(python3)
BuildRequires:	python%{pyver}dist(cython)
BuildRequires:	python%{pyver}dist(hatchling)
BuildRequires:	python%{pyver}dist(pip)
BuildRequires:	python%{pyver}dist(pytest)
BuildRequires:	python%{pyver}dist(setuptools)
BuildRequires:	python%{pyver}dist(wheel)

Provides:       bundled(llhttp)

%description
httptools is a Python binding for the nodejs HTTP parser.

%prep
%autosetup -p1 -n %{module}-%{version}
# remove cypthon pregens
rm $(grep -rl '/\* Generated by Cython')
# remove bundled egg-info
rm -rf %{module}.egg-info

# move vendored licenses
mv vendor/llhttp/LICENSE-MIT LICENSE.llhttp
mv vendor/http-parser/LICENSE-MIT LICENSE.http-parser

%build
%py_build

%install
%py3_install

%if %{with test}
%check
pip install -e .[test]
%{__python} -m pytest -v tests/
%endif

%files
%{python3_sitearch}/%{module}
%{python3_sitearch}/%{module}-%{version}*.egg-info
%license LICENSE
%license LICENSE.llhttp
%license LICENSE.http-parser