%define module httptools
%bcond tests 1

Name:		python-httptools
Summary:	A Python binding for the nodejs HTTP parser
Version:	0.8.0
Release:	1
License:	MIT
Group:		Development/Python
URL:		https://github.com/MagicStack/httptools
Source0:	%{URL}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildSystem:	python
BuildRequires:	http-parser-devel
BuildRequires:	pkgconfig(libllhttp)
BuildRequires:	pkgconfig(python)
BuildRequires:	python%{pyver}dist(cython)
BuildRequires:	python%{pyver}dist(hatchling)
BuildRequires:	python%{pyver}dist(pip)
BuildRequires:	python%{pyver}dist(setuptools)
BuildRequires:	python%{pyver}dist(wheel)
%if %{with tests}
BuildRequires:	python%{pyver}dist(pytest)
%endif

%description
httptools is a Python binding for the nodejs HTTP parser.

%prep -a
# Remove cypthon pregens
rm -f $(grep -rl '/\* Generated by Cython')
# Remove bundled egg-info
rm -rf %{module}.egg-info

# Use system http-parser
sed -i 's/use_system_http_parser = False/use_system_http_parser = True/' setup.py
rm -rf vendor/http-parser

# Use system llhttp
sed -i 's/use_system_llhttp = False/use_system_llhttp = True/' setup.py
rm -rf vendor/llhttp

%build -p
export LDFLAGS="%{ldflags} -lpython%{pyver}"

%if %{with tests}
%check
export CI=true
export PYTHONPATH="%{buildroot}%{python_sitearch}"
pytest tests/
%endif

%files
%doc README.md
%{python_sitearch}/%{module}
%{python_sitearch}/%{module}-%{version}.dist-info
